server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

regCenter:
  serverList: 127.0.0.1:2181
  namespace: elastic-job-example
  baseSleepTimeMilliseconds: 1000
  maxSleepTimeMilliseconds: 3000
  maxRetries: 3

jobs:
  dataflowJob:
    cron: 0 * 5 * * ?
    shardingTotalCount: 3
    shardingItemParameters: 0=1,1=2,2=3

  simpleJob:
    cron: 0 * 5 * * ?
    shardingTotalCount: 3
    shardingItemParameters: 0=1,1=2,2=3